version: '2'

services:
    hospeda.app:
        container_name: hospeda.app
        build:
            context: .
            dockerfile: docker-build
        volumes:
            - ./:/aplicacao
        environment: 
            - ENVIROMENT=production
            - URL=http://localhost
            - PORT=80